import { useEffect, useState } from 'react'
import { getApplication, sendFeedback } from '../api.js'
import DecisionChip from './DecisionChip.jsx'
import { RiskMeter } from './Queue.jsx'

const ACTION = {
  ALLOW: 'Proceed with the application',
  STEP_UP: 'Challenge with OTP / liveness before proceeding',
  REVIEW: 'Hold for manual fraud review',
  BLOCK: 'Block and raise a fraud case',
}

export default function CaseDetail({ applicationId, onReviewed }) {
  const [detail, setDetail] = useState(null)
  const [busy, setBusy] = useState(false)

  useEffect(() => {
    if (!applicationId) return setDetail(null)
    let live = true
    getApplication(applicationId).then((data) => live && setDetail(data)).catch(() => {})
    // the AI narrative is generated after the decision, so re-read once it lands
    const timer = setTimeout(
      () => getApplication(applicationId).then((data) => live && setDetail(data)).catch(() => {}),
      2500,
    )
    return () => { live = false; clearTimeout(timer) }
  }, [applicationId])

  if (!applicationId) {
    return <aside className="card detail empty muted">Select an application to see why it was decided that way.</aside>
  }
  if (!detail) return <aside className="card detail muted">Loading case…</aside>

  async function review(label) {
    setBusy(true)
    try {
      await sendFeedback(applicationId, label)
      setDetail({ ...detail, label })
      onReviewed?.()
    } finally {
      setBusy(false)
    }
  }

  const narrative = detail.narrative

  return (
    <aside className="card detail">
      <header>
        <div>
          <h2>{detail.applicant_name}</h2>
          <p className="muted mono small">{detail.application_id} · device {detail.device_id}</p>
        </div>
        <DecisionChip decision={detail.decision} />
      </header>

      <p className="action">{ACTION[detail.decision]}</p>
      <RiskMeter score={detail.risk_score} decision={detail.decision} />

      <h3>Score composition</h3>
      <ul className="bars">
        <ScoreBar label="Supervised model" value={detail.ml_score} weight="0.55" />
        <ScoreBar label="Anomaly / novelty" value={detail.anomaly_score} weight="0.20" />
        <ScoreBar label="Rule pack" value={detail.rule_score} weight="0.25" />
      </ul>

      <h3>Evidence</h3>
      <ol className="reasons">
        {detail.reasons.map((reason, index) => (
          <li key={index}>
            <span className={`badge ${reason.type}`}>{reason.type}</span>
            {reason.detail}
          </li>
        ))}
      </ol>

      <h3>Matched typologies</h3>
      <ul className="typologies">
        {detail.typologies.map((typology) => (
          <li key={typology.title}>
            <b>{typology.title}</b> <span className="muted small">similarity {typology.similarity}</span>
            <p className="muted small">{typology.controls}</p>
          </li>
        ))}
      </ul>

      <h3>AI analyst summary</h3>
      {narrative ? (
        <div className="narrative">
          <p>{narrative.summary}</p>
          <p className="muted small">
            Typology: {narrative.typology} · advisory action: {narrative.recommended_action.replace(/_/g, ' ')} ·
            confidence {narrative.confidence}
          </p>
          <ul>{narrative.analyst_checks.map((check) => <li key={check}>{check}</li>)}</ul>
          <p className="muted small footnote">
            Generated by {narrative.source}. Explanation only — the decision above was made by the
            rules and models, not by the language model.
          </p>
        </div>
      ) : (
        <p className="muted small">Generating explanation…</p>
      )}

      <h3>Analyst verdict</h3>
      {detail.label === null || detail.label === undefined ? (
        <div className="verdict">
          <button className="danger" disabled={busy} onClick={() => review(1)}>Confirm fraud</button>
          <button disabled={busy} onClick={() => review(0)}>Mark legitimate</button>
        </div>
      ) : (
        <p className="muted small">
          Marked {detail.label === 1 ? 'fraud' : 'legitimate'}
          {detail.reviewed_by ? ` by ${detail.reviewed_by}` : ''} — feeds the next retrain.
        </p>
      )}
    </aside>
  )
}

function ScoreBar({ label, value, weight }) {
  return (
    <li>
      <span className="bar-label">{label} <span className="muted small">weight {weight}</span></span>
      <span className="bar"><span className="bar-fill" style={{ width: `${value * 100}%` }} /></span>
      <span className="mono small">{value.toFixed(2)}</span>
    </li>
  )
}
